//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 imageProcessing.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_imageProcessingTYPE         130
#define ID_IMAGEPROCESSING_OPENABMPFILE 32771
#define ID_IMAGEPROCESSING_SAVETONEWBMP 32772
#define ID_IMAGEPROCESSING_DISPLAYBMPFILEHEADER 32773
#define ID_IMAGEPROCESSING_DISPLAYPALETTE 32774
#define ID_IMAGEPROCESSING_GETPIXELVALUE 32775
#define ID_IMAGEPROCESSING_SETPIXELVALUE 32776
#define ID_IMAGEPROCESSING_IMAGEINERPOLATION 32777
#define ID_IMAGEPROCESSING_MEDIANFILTERING 32778
#define ID_IMAGEPROCESSING_GAUSSIANSMOOTHING 32779
#define ID_IMAGEPROCESSING_BILATERALFILTERING 32780
#define ID_IMAGEPROCESSING_HISTOGRAMEQUALIZATION 32781
#define ID_IMAGEPROCESSING_SHARPENINGBYGRADIENT 32782
#define ID_IMAGEPROCESSING_CANNYEDGEDETECTION 32783
#define ID_IMAGEPROCESSING_OTSUTHRESHOLDING 32784
#define ID_IMAGEPROCESS_OPENBMPFILE     32785
#define ID_IMAGEPROCESS_SAVETOFILE      32786
#define ID_IMAGEPROCESS_DISPLAYFILEHEADER 32787
#define ID_IMAGEPROCESS_DISPLAYPALETTE  32788
#define ID_IMAGEPROCESS_GETPIXELVALUE   32789
#define ID_IMAGEPROCESS_SETPIXELVALUE   32790
#define ID_IMAGEPROCESS_INERPOLATION    32791
#define ID_IMAGEPROCESS_GAUSSSMOOTH     32792
#define ID_IMAGEPROCESS_MEDIANFILTER    32793
#define ID_IMAGEPROCESS_BILATERALFILTER 32794
#define ID_IMAGEPROCESS_HISTOEQUALIZATION 32795
#define ID_IMAGEPROCESS_SHARPENGRAD     32796
#define ID_IMAGEPROCESS_CANNYEDGE       32797
#define ID_IMAGEPROCESS_OTSUSEGMENT     32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
